[pytest]

# log_cli = true
# log_cli_level = DEBUG
# log_format = %(asctime)s %(levelname)s %(message)s
# log_date_format = %H:%M:%S

pythonpath = .

addopts = --browser chromium --browser firefox --browser webkit

markers =
    api: API autotests
    ui: UI autotests
    test: Debug of local tests
    admin_session: Admin logs in before the tests
    user_session(count): User logs in before the tests with *count* value of users in environment
    browsers(names): Tests for only current browsers (chromium|firefox|webkit)
    check_all_users_change(delta, username_source, should_exist): Do GET /admin/users before and after the test and assert delta/existence.
    check_accounts_change(delta): Do GET /customer/accounts before and after the test and assert delta.
    entity_will_be_created(*sources): Add entity/entities to created_objects for cleanup. Example: @pytest.mark.entity_will_be_created("new_user_request")
    api_version(name): Backend version tag for tests (e.g. with_database)