server=http://localhost:4111/api
api_version=/v1
backendUrl = http://localhost:4111/api/v1

UI_BASE_URL=http://localhost:3000
MODEL_COMPARISON_CONFIG_FILE=model-comparison.properties

ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
ADMIN_ROLE=ADMIN