[DEFAULT]
# Format:
# LeftClass=RightClass:field_left=field_right,field_left2=field_right2
CreateUserResponse=UserDao:username=username,role=role
CreateAccountResponse=AccountDao:accountNumber=account_number,balance=balance
CustomerResponse=UserDao:username=username,role=role,name=name
DepositMoneyResponse=AccountDao:accountNumber=account_number,balance=balance
TransferMoneyResponse=TransactionsDao:amount=amount