# Format: RequestClass=ResponseClass:field_request1=field_response1,field_request_2=field_response_2

[DEFAULT]
CreateUserRequest=CreateUserResponse:username=username,role=role
CreateUserResponse=CreateUserRequest:username=username,role=role
LoginUserRequest=LoginUserResponse:username=username
CreateAccountResponse=CreateAccountResponse:id=id,accountNumber=accountNumber,balance=balance
TransferResponseFraudCheck=TransferResponseFraudCheck:status=status,message=message,amount=amount,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,fraudRiskScore=fraudRiskScore,fraudReason=fraudReason,requiresManualReview=requiresManualReview,requiresVerification=requiresVerification