env:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fluent-bit-es-credentials
        key: ES_PASSWORD

config:
  # [INPUT] читает все логи контейнеров из /var/log/containers/*.log
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On

  # [FILTER] — обогащает логи метаданными K8s (имя пода, namespace, labels);
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Labels Off
        Annotations Off
    
    # Оставляем только логи backend
    [FILTER]
        Name grep
        Match kube.*
        Regex $kubernetes['container_name'] ^backend$
    
    # Убираем лишние kubernetes-поля
    [FILTER]
        Name modify
        Match kube.*
        Remove kubernetes
        Remove stream
        Remove time
        Remove _p
        Remove logger_name
        Remove thread_name
        Remove timestamp

  # [OUTPUT] — шлёт в Elasticsearch по адресу elasticsearch-master:9200
  # HTTP_Passwd ${ES_PASSWORD} — пароль из переменной, которая придёт из Secret'а.
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Port 9200
        Logstash_Format On
        Logstash_Prefix nbank
        Retry_Limit False
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd ${ES_PASSWORD}
        Suppress_Type_Name On